config/routes.rb
Rails.application.routes.draw do
 



  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  post '/signout' => 'sessions#destroy'
  post '/addresses/new' => 'addresses#create'
  post '/details/new' => 'details#create'
  get '/user/address' => 'users#address' 
  post '/user/address' => 'users#address'
  get 'employee' => 'static_pages#employee'
  get '/auth/facebook/callback' => 'employees#create'

  resources :employees
  resources :followups
  resources :details
  resources :addresses 
  resources :users

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
end

app/views/welcome/index.html.erb
      <!-- Intro/Welcome/Logo/Tagline -->

      <div class="intro">
         <img src="http://www.iamthemodernman.biz/internet/2/images/router3.png" alt="Router" height="250" width="325">
         <h1>SHARE YOUR INTERNET</h1>
         <img src="http://www.iamthemodernman.biz/internet/2/images/wifi100icon.png" alt="wifi symbol" height="50" width="50">
         <h2>Share Wi-Fi With Neighbors And Save</h2>

       <% if !logged_in? %>
         <%= button_to "Start Here", new_user_path, :class => "btn btn-lg btn-outline", :method => :get %>
       <% else %>
         <%= button_to "Start Here", users_path, :class => "btn btn-lg btn-outline", :method => :get %>
       <% end %> 






      </div>


      <!-- How It Works/About -->


      <div class="about">
         <h1>How It Works</h1>
         <img src="http://www.iamthemodernman.biz/internet/2/images/steps.png" alt="How It Works" height="378" width="455">
         <h1><a href="#" class="altbtn altbtn-lg altbtn-outline">Read More</a></h1>
      </div>